behaviors:
  OctagonAgentSocial:
    trainer_type: ppo
    max_steps: 20000000          # Total training steps
    time_horizon: 128            # How many steps of experience per agent before updating
    summary_freq: 20000          # How often stats are written to TensorBoard
    keep_checkpoints: 5
    checkpoint_interval: 50000

    hyperparameters:
      batch_size: 512           # Number of experiences used per training batch
      buffer_size: 2048         # How many total experiences are collected before training
      learning_rate: 3.0e-4
      beta: 5.0e-3
      beta_schedule: linear
      epsilon: 0.2
      lambd: 0.95
      num_epoch: 3

    network_settings:
      normalize: false
      hidden_units: 512         # Size of each hidden layer
      num_layers: 2              # How deep the network is
      #vis_encode_type: resnet    # Visual encoder type: simple, nature_cnn, resnet
      memory:
        sequence_length: 128
        memory_size: 512

    reward_signals:
      extrinsic:
        gamma: 0.99
        strength: 1.0

      rnd:
        gamma: 0.99
        strength: 0.01 # if exploration is too low up to 0.1
        learning_rate: 0.0001

    init_path: "Assets/AgentBrains/SoloBrainRun0.onnx" # insert solo brain

    self_play:
      window: 10
      play_against_latest_model_rationale: 0.5
      save_steps: 10000     # How often to save self-play models
      swap_steps: 5000      # How often to swap self-play models
      team_change: 5000 
    